[site]
bucket = "./out"
entry-point = "."

[site.static]
include = ["_headers", "_redirects", "_routes.json"]

[env.production]
name = "droit-site"
route = ""
workers_dev = true
compatibility_date = "2023-05-14"

[env.production.build]
command = "npm run build"
output_directory = "out"

[[env.production.routes]]
pattern = "/*"
script = ""

[[env.production.routes]]
pattern = "/admin/*"
script = ""
custom_domain = true

# Add Pages configuration
pages_build_output_dir = "out"

# Custom routes for admin
[[routes]]
pattern = "/admin"
script = ""
custom_domain = true

[[routes]]
pattern = "/admin/*"
script = ""
custom_domain = true 