[site]
bucket = "./out"
entry-point = "."

[site.static]
include = ["_headers", "_redirects"]

[env.production]
name = "droit"
route = ""
workers_dev = true
compatibility_date = "2023-05-14"

[env.production.build]
command = "npm run build"
output_directory = "out"

[[env.production.routes]]
pattern = "/*"
script = "" 