[site]
bucket = "./out"
entry-point = "."

[site.static]
include = ["_headers", "_redirects", "_routes.json"]

[env.production]
name = "droit"
route = ""
workers_dev = true
compatibility_date = "2023-12-01"

[env.production.build]
command = "npm run build"
output_directory = "out"

[[env.production.routes]]
pattern = "/*"
script = ""

[[env.production.routes]]
pattern = "/admin/*"
script = ""
custom_domain = true

# Add Pages configuration
pages_build_output_dir = "out"

# Variable bindings. These are arbitrary, plaintext strings (similar to environment variables)
# Note: Use secrets to store sensitive data.
# Docs: https://developers.cloudflare.com/workers/platform/environment-variables
# [vars]
# MY_VARIABLE = "production_value"

# Bind a KV Namespace. Use KV as persistent storage for small key-value pairs.
# Docs: https://developers.cloudflare.com/workers/runtime-apis/kv
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" 

# Custom routes for admin
[[routes]]
pattern = "/admin"
script = ""
custom_domain = true

[[routes]]
pattern = "/admin/*"
script = ""
custom_domain = true
