backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
  site_url: https://sage-queijadas-0f917a.netlify.app # Netlify site URL for authentication

media_folder: "public/images/uploads" # Media files will be stored in the repo under public/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

# Display the preview link after a publish, defaults to false
show_preview_links: true

# This is where your site will be published
display_url: https://fpra-droits.org # Your Cloudflare Pages URL or custom domain

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home Page"
        file: "content/home.json"
        fields:
          - { label: "Hero Title", name: "heroTitle", widget: "string" }
          - { label: "Hero Description", name: "heroDescription", widget: "text" }
          - { label: "Hero Button Text", name: "heroButtonText", widget: "string" }
          - label: "Features"
            name: "features"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Icon", name: "icon", widget: "string", hint: "Icon name from React Icons" }
  
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" } 